### ISSUE TITLE
Normalisation of timestamps that don't round cleanly

### ISSUE THREAD

**Issue by jamesba** [bbc/rd-apmm-python-lib-mediatimestamp#28]
It is currently possible to construct a range which will normalise such that:

```pycon
>>> list(tr.normalise(n, d, TimeRange.ROUND_OUT).at_rate(n, d))[1] == tr.start
True
```

Eg.

```pycon
>>> gen = TimeRange.from_str("[0:21333333_1:0]").normalise(48000, 1024, TimeRange.ROUND_OUT).at_rate(48000, 1024)
>>> next(gen)
TimeOffset.from_str("0:0")
>>> next(gen)
TimeOffset.from_str("0:21333333_1")
```
This is technically correct behaviour since:

```pycon
>>> TimeOffset.from_str("0:21333333").normalise(48000, 1024, TimeOffset.ROUND_DOWN)
TimeOffset.from_str("0:0")
```

even though

```pycon
>>> TimeOffset.from_count(0, 48000, 1024)
TimeOffset.from_str("0:21333333")
```

is correct, but it is definitely confusing.

Perhaps the behaviour of ```ROUND_OUT``` should be changed so that the end timestamps are only rounded down if not equal to the output of ```from_count```.

**Comment by j616** [comment]
Moved to pivotal https://www.pivotaltracker.com/story/show/176676609
