### ISSUE TITLE
Union of range and empty range isn't possible

### ISSUE THREAD

**Issue by jamesba** [bbc/rd-apmm-python-lib-mediatimestamp#29]
```python
TimeRange.never().union_with_timerange(A) == A
```

Should be true for any TimeRange A. Currently this instead raises an exception.

Relatedly:

```python
TimeRange.never().is_contiguous_with_timerange(A)
```
should also always be True

**Comment by alexrawcliffe** [comment]
Resolved in https://github.com/bbc/rd-apmm-python-lib-mediatimestamp/pull/30
