### ISSUE TITLE
Dateutil version capped at <2.8.1

### ISSUE THREAD

**Issue by alexrawcliffe** [bbc/rd-apmm-python-lib-mediatimestamp#38]
Tagging @bbc/rd-apmm-cloudfit 

Capped here: https://github.com/bbc/rd-apmm-python-lib-mediatimestamp/pull/37
In response to https://github.com/boto/boto3/commit/c84bb4095fb69eb2d77fe72cfd17ce7654737ef2
Which pulls in this change from botocore:
https://github.com/boto/botocore/commit/e87e7a745fd972815b235a9ee685232745aa94f9

Should uncap as soon as boto project sorts itself out.

**Comment by simonrankine** [comment]
This should be reviewed when the constraints work is finished, as I suspect may allow us to at least close this issue and manage it centrally.

**Comment by j616** [comment]
Moved to pivotal https://www.pivotaltracker.com/story/show/176676415
